### ISSUE TITLE
Expand(dictionary) doesn't seem to work

### ISSUE THREAD

**Issue by SGStino** [jehugaleahsa/Earl#1]
I tried using the library, but Expand with an IDictionary<string, object>/expandoobject doesn't seem to work.

I'll send a pull request if i managed to fix it. But that will probably have the projects updated to vs2017 xproj projects instead of project.json.

**Comment by SGStino** [comment]
pull request added: #2

**Comment by jehugaleahsa** [comment]
So was the underlying issue that your `ExpandoObject` has unrecognized property types. I am looking at your changes and they look pretty solid. Thanks for upgrading the .NET Core version.

**Comment by jehugaleahsa** [comment]
I was able to merge your code changes to support additional types. However, when I tried to apply your solution and csproj changes I encountered issues. 

I reverted back the last two commits and then upgraded to .NET 4.5.1 (still .NETStandard1.6), since my development machine no longer has 4.5 installed (that's what's in the README anyway).

I published to NuGet as 0.1.1.0, so you should see those changes included. Let me know if you encounter any issues.

**Comment by SGStino** [comment]
The solution and csproj changes require vs2017, but i checked in as separate commits so you could avoid getting these changes. Thanks for upgrading the nuget!

**Comment by jehugaleahsa** [comment]
I randomly discovered the trick `Value?.GetType() ?? typeof(TValue)` doesn't work for nullable types in some cases. Consider a `int?`: if it is `null`, `int?` will be returned. However, the nullable-ness disappears when the value is boxed (stored as an object), in which case `GetType()` will return `int`, not `int?`. The correct solution is to say:

```csharp
object value = Value;
Type inferredType = typeof(TValue);
if (value == null)
{
    return inferredType;
}
Type actualType = value.GetType();
if (Nullable.GetUnderlyingType(inferredType) == actualType)
{
    return inferredType;
}
return actualType;
```

I am not sure if this will impact the functionality in Earl. I will try to generate a test that illustrates the issue.

**Comment by SGStino** [comment]
I'm not sure if it matters that much if it is "int" or "int?", as the type is only used to pick the correct conversion later on, aka: is it a complex type or a primitive. 
Because an int? with a value is just an int as far as we're concerned, isn't it?

But I do see an issue when it's actually null, then the method will return typeof(TValue), where TValue is a object in the case of ExpandoObjects/IDictionary<string,object>.
